
configuration:
  - Release

install:
  - cinst --allow-empty-checksums smlnj
  - cinst wget
  - c:\ProgramData\chocolatey\bin\wget.exe https://github.com/polyml/polyml/releases/download/v5.7/PolyML5.7-64bit.msi
  - ps: Install-Package -Force .\PolyML5.7-64bit.msi

build_script:
  - cmd: test\simpletest.bat

