dist:
  - trusty

language:
  - cpp

sudo:
  - false

os:
  - linux

addons:
  apt:
    packages:
      - mlton
      - smlnj
      - libsmlnj-smlnj
      
script:
  - make test
  - make clean  # so we rebuild the aggregated vext.sml
  - make test


  
