dist:
  - trusty

language:
  - cpp

sudo:
  - false

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - mlton
      - smlnj
      - libsmlnj-smlnj
      - polyml

before_install:
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]] ; then brew update ; brew install mlton smlnj polyml mlkit ; fi
      
script:
  - make clean  # so we rebuild the aggregated repoint.sml
  - make test-all
  
