
# Different build from the usual here: we concat the source files into
# a single deployment file with no dependencies other than Basis. But
# we also build from the multiple sources in order to get proper
# compiler error reporting.

vext:	vext.sml
	../sml-buildscripts/polybuild src/vext.mlb
	mlton $<

SOURCES	:= \
	src/version.sml \
	src/types.sml \
	src/filebits.sml \
	src/control.sml \
	../sml-simplejson/json.sml \
	src/jsonbits.sml \
	src/provider.sml \
	src/hg.sml \
	src/git.sml \
	src/app.sml \
	src/main.sml

vext.sml:	$(SOURCES)
	@echo "(* This file is automatically generated from the individual " > $@
	@echo "   source files in the Vext repository. *)" >> $@
	@echo >> $@
	cat $^ >> $@

clean:
	rm -f vext.sml vext src/vext

