name: Linux CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: deps
      run: sudo apt-get install mlton smlnj libsmlnj-smlnj polyml libpolyml-dev
    - name: prepare
      run: |
        git config --global user.email "nobody@example.com"
        git config --global user.name "Nobody"
        make clean   # so we rebuild the aggregated repoint.sml
    - name: make
      run: make
    - name: test
      run: make test-all
