name: macOS CI

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: deps
      run: |
        # Used to have mlkit here as well, but Homebrew is refusing to
        # install it at the moment for some reason
        brew install mercurial mlton polyml
        brew install --cask smlnj
    - name: prepare
      run: |
        git config --global user.email "nobody@example.com"
        git config --global user.name "Nobody"
        make clean   # so we rebuild the aggregated repoint.sml
    - name: make
      run: make
    - name: test
      run: PATH=$(brew --prefix)/smlnj/bin:"$PATH" make test-all
